[project]
name = "xorq-plugins"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
test = [
    "pytest",
    "xorq",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.10",
    "xorq>=0.3.19",
]
